# Generated by Django 4.0.1 on 2022-03-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0002_alter_curriculum_id'),
        ('userManage', '0002_employee_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='clazz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='infoManage.clazz'),
        ),
    ]
