# Generated by Django 4.0.1 on 2022-03-02 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0002_alter_curriculum_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManage', '0003_employee_clazz'),
    ]

    operations = [
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('describe', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('registredTime', models.DateTimeField(auto_now=True)),
                ('recentLoginTime', models.DateTimeField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20, null=True)),
                ('describe', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('registredTime', models.DateTimeField(auto_now=True)),
                ('recentLoginTime', models.DateTimeField(default=None)),
                ('clazz', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='infoManage.clazz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
