# Generated by Django 4.0.1 on 2022-02-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(help_text='信息技术与计算机系', max_length=20, verbose_name='系别')),
                ('specialist', models.CharField(help_text='例:软件工程', max_length=20, verbose_name='专业')),
                ('clazz_num', models.CharField(help_text='例:1909', max_length=20, verbose_name='数字班号')),
                ('clazz_brief', models.CharField(help_text='例:软件1909班', max_length=20, verbose_name='简称')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级管理',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(blank=True, max_length=30, null=True, verbose_name='教授班级')),
                ('description', models.TextField(blank=True, help_text='填写办公室信息，邮箱电话等', max_length=200, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=25, verbose_name='姓名')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师管理',
            },
        ),
        migrations.CreateModel(
            name='tUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='课程完整名')),
                ('brief_name', models.CharField(max_length=20, verbose_name='课程简名')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='教授', to='infoManage.professor')),
            ],
            options={
                'verbose_name_plural': '课程管理',
            },
        ),
    ]
