# Generated by Django 4.0.1 on 2022-04-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0002_alter_curriculum_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tUser',
        ),
    ]
