# Generated by Django 4.0.1 on 2022-02-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicSubmits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='relateCurriculum',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='publicSubmits.curriculum', verbose_name='所属课程'),
        ),
    ]
