# Generated by Django 4.0.1 on 2022-02-20 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicSubmits', '0002_alter_filesmodel_relatecurriculum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师管理'},
        ),
        migrations.AddField(
            model_name='professor',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='教授', to='publicSubmits.professor'),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='relateAssignment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicSubmits.assignment', verbose_name='所属作业'),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='relateCurriculum',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicSubmits.curriculum', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='relateUser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(default='Noneee', max_length=25, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
