# Generated by Django 4.0.1 on 2022-02-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSubmits', '0003_alter_professor_options_professor_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(help_text='信息技术与计算机系', max_length=20, verbose_name='系别')),
                ('specialist', models.CharField(help_text='例:软件工程', max_length=20, verbose_name='专业')),
                ('clazz_num', models.CharField(help_text='例:1909', max_length=20, verbose_name='数字班号')),
                ('clazz_brief', models.CharField(help_text='例:软件1909班', max_length=20, verbose_name='简称')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师管理',
            },
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
