# Generated by Django 4.0.1 on 2022-02-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSubmits', '0004_clazz_alter_curriculum_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
            ],
        ),
    ]
