# Generated by Django 4.0.1 on 2022-02-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicSubmits', '0005_tuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tUser',
        ),
    ]
