# Generated by Django 4.0.1 on 2022-02-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0001_initial'),
        ('publicSubmits', '0006_delete_tuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clazz',
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='relateCurriculum',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='infoManage.curriculum', verbose_name='所属课程'),
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
