# Generated by Django 4.0.1 on 2022-02-20 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoManage', '0002_alter_curriculum_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicSubmits', '0007_delete_clazz_alter_filesmodel_relatecurriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='relateCurriculum',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='infoManage.curriculum', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='relateUser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
