# Generated by Django 4.0.1 on 2022-02-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicSubmits', '0010_alter_filesmodel_relateuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name_plural': '作业收集提交'},
        ),
        migrations.AlterModelOptions(
            name='filesmodel',
            options={'verbose_name_plural': '提交文件管理'},
        ),
    ]
