# Generated by Django 4.0.1 on 2022-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSubmits', '0011_alter_assignment_options_alter_filesmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
