# Generated by Django 4.0.1 on 2022-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSubmits', '0012_alter_filesmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='file',
            field=models.FileField(upload_to='uploads/assignment'),
        ),
    ]
