# Generated by Django 4.0.1 on 2022-02-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicSubmits', '0013_alter_filesmodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='describe',
            new_name='assignmentDescribe',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='file_type',
            new_name='fileDescribe',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assginName',
            new_name='fileNameRule',
        ),
    ]
