# Generated by Django 4.0.1 on 2022-02-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicSubmits', '0014_rename_describe_assignment_assignmentdescribe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='relateCurriculum',
        ),
    ]
