# Generated by Django 4.0.1 on 2022-02-25 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicSubmits', '0017_filesmodel_filename_alter_assignment_filedescribe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': '作业规则', 'verbose_name_plural': '作业收集提交'},
        ),
        migrations.AlterModelOptions(
            name='filesmodel',
            options={'verbose_name': '提交文件', 'verbose_name_plural': '提交文件管理'},
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='file',
            field=models.FileField(upload_to='assignment/', verbose_name='文件下载'),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='relateUser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relateUser', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
