# Generated by Django 4.0.1 on 2022-04-04 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0008_alter_userinfo_recentlogintime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicSubmits', '0018_alter_assignment_options_alter_filesmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='relateUserInfo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManage.userinfo', verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='relateUser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relateUser', to=settings.AUTH_USER_MODEL, verbose_name='所属用户(旧)'),
        ),
    ]
