# Generated by Django 4.0.1 on 2022-04-04 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0008_alter_userinfo_recentlogintime'),
        ('publicSubmits', '0019_filesmodel_relateuserinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='relateUser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relateUser', to='userManage.userinfo', verbose_name='所属用户(旧)'),
        ),
    ]
