# Generated by Django 4.0.1 on 2022-04-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicSubmits', '0020_alter_filesmodel_relateuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesmodel',
            name='relateUserInfo',
        ),
    ]
